project:
  type: website
  output-dir: docs

website:
  title: "I'm Scarlet."
  navbar:
    left:
      - href: index.qmd
        text: Bio
      - href: about.qmd
        text: CV

format:
  html:
    theme: journal
    css: styles.css
    toc: true
